// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.founder.proto;

public interface StreamRquestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.founder.proto.StreamRquest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_info = 1;</code>
   */
  java.lang.String getRequestInfo();
  /**
   * <code>string request_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestInfoBytes();
}
